Repository nexmo-community/build-a-thing-video, pull requests merged in 2020-10, with the labels that each got.

#11 Basic styling for the index and room pages
  client/index.html
  client/room.html
  client/style.css
Labels: hacktoberfest

#15 Implemented signalling for chat, applied styling
  client/room.html
  client/style.css
Labels: enhancement

#17 Fix broken links in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-approved

#20 Fix exception handling
  functions/session.js
Labels: hacktoberfest

#21 Three Features: Lock Room, Add Name to Video Card, and Add Name to Chat Message
  client/access-required.html
  client/index.html
  client/room.html
  client/style.css
  functions/session.js
Labels: hacktoberfest

#29 Adhear => adhere
  .github/CONTRIBUTING.md
Labels: hacktoberfest

#30 Add pronouns feature
  client/index.html
  client/room.html
  client/style.css
Labels: hacktoberfest

#31 Refactor `created` function from room.html
  client/room.html
Labels: hacktoberfest
